Fixes #1160: Moved some high frequency info level logs to debug.
skupperproject/skupper-router pull request #1161
Opened 2023-07-12 14:34 UTC by ganeshmurthy

Added some new info level logs that show up on router schema changes.

2023-07-12 15:29 UTC, ted-ross commented on src/vanflow.c
> +    qd_log(LOG_FLOW_LOG, QD_LOG_DEBUG, "%s", line);
I think this is the one you must not change.  This removes ALL flow-related content from the logs.

2023-07-12 15:30 UTC, ted-ross requested changes
Looks good overall.  I have one comment that we should discuss before you merge.

2023-09-26 18:38 UTC, kgiusti commented on src/router_core/connections.c
> +    // High frequency log message, setting to QD_LOG_DEBUG
Also maybe add the "role=<role>" to the log?

2023-09-26 18:38 UTC, kgiusti commented on src/router_core/connections.c
> +    qd_log(LOG_ROUTER_CORE, QD_LOG_DEBUG, "[C%" PRIu64 "] Connection Closed", conn->identity);
Ditto INFO if backbone conn?

2023-09-26 18:41 UTC, kgiusti approved these changes
Some inline nits - only suggestions for you to consider.

2023-09-26 19:01 UTC, ganeshmurthy commented on src/router_core/connections.c
> +    // High frequency log message, setting to QD_LOG_DEBUG
I have made the requested changes. Please take a look.

2023-09-26 19:40 UTC, merged