Fixes #1472: Removed the adaptor_finalizing flag. Moved connection fr…
skupperproject/skupper-router pull request #1485
Opened 2024-04-25 14:29 UTC by ganeshmurthy

…ee loop to ADAPTOR_final().

Also introduced connector and listener incref and decref functions to be able to safely free connectors and listeners

2024-04-30 14:14 UTC, kgiusti requested changes
Some comment's don't apply to this patch and can be handled in a follow up patch.

Of all the comments I think the ADAPTOR_final cleanup refcounting needs to be addressed (assuming I'm correct regarding the possible double free).

2024-04-30 14:14 UTC, kgiusti commented on src/adaptors/tcp/tcp_adaptor.c
> +        qd_tcp_listener_decref(listener);
This call to decref may crash if the last closed tcp conn is the last entity holding the listener decref - in that case close_connection_XSIDE_IO will drop the refcount to zero and free the listener.

Same issue applies to the decref of the connector as well.

Fixing that may be tricky...

Without too much "brain smart-making" you could try the following hack:

1. modify the _decref() functions to return "true" if the listener/connector was freed else false
2. at the top of the while loop calll _incref before closing any connections. That ensures that the listener/connector won't be freed by any of the connections closing
3. after closing connections, loop calling _decref() until true is returned.

That's pretty hacky.  You could also fetch the refcount before freeing conns and only call _decref if the total number of conns (DEQ_SIZE) is less than the original refcount.

Hackity hack hack!

2024-04-30 17:30 UTC, ganeshmurthy commented on src/adaptors/tcp/tcp_adaptor.c
> +        qdr_connection_closed(connector->core_conn);
Done ! Thanks.

2024-04-30 19:07 UTC, ganeshmurthy commented on src/adaptors/tcp/tcp_adaptor.c
> +        qd_tcp_listener_decref(listener);
Done !

2024-04-30 19:10 UTC, ganeshmurthy commented on src/adaptors/tcp/tcp_adaptor.c
>      if (!!conn->common.parent && conn->common.parent->context_type == TL_LISTENER) {
Done !

2024-04-30 19:21 UTC, ganeshmurthy commented on src/adaptors/tcp/tcp_adaptor.c
> +    // Call connector incref when a connection associated with the connector is added (DEQ_INSERT_TAIL(connector->connections, conn))
Done !

2024-04-30 19:21 UTC, ganeshmurthy commented on src/adaptors/tcp/tcp_adaptor.c
> +    // Call listener incref when a connection associated with the listener is added (DEQ_INSERT_TAIL(listener->connections, conn))
Done !

2024-05-01 15:03 UTC, kgiusti approved these changes
Excellent! Ship it.

2024-05-01 15:20 UTC, merged