Fixes #730: document inter-router protocol
skupperproject/skupper-router pull request #975
Opened 2023-03-06 16:10 UTC by mgoulish

2023-06-09 16:37 UTC, ted-ross requested changes
This is a good start in that it shows where to look for various parts of inter-router communication.  I think there are some background topics that might make the sequence easier to express:
 - The data structures that support routing (addresses and nodes)
 - The protocol between the routers (MAR, MAU, sequence numbers, etc.)

2023-06-09 16:37 UTC, ted-ross commented on docs/notes/router-communicates-new-address.adoc
> +   the direction of this link is incoming or ougoing.
Typo here.

2023-06-09 16:37 UTC, ted-ross commented on docs/notes/router-communicates-new-address.adoc
> +=== At Attach Time
It's not clear what is attaching here.  Are you referring to the sender on router B or the receiver on router A?

2023-06-09 16:37 UTC, ted-ross commented on docs/notes/router-communicates-new-address.adoc
> +3. qcm_mobile_sync_on_mau_CT finds the ID field of the router that this mobile address update came from, and calls qcm_mobile_sync_router_by_id to retrieve that router's node structure. It adds this
Step 3 is glossing over a lot of important detail.  Remote routers are designated by a mask bit.  The address that is created upon receiving the MAU has a bitmask in it which indicates the set of routers on which there is at least one receiver for the address.  If there are already inbound links for the address and this is the first reachable destination, then the inbound links are "started" which means that credit is granted, allowing the senders to begin flowing traffic.

2024-02-20 15:24 UTC, mgoulish commented
Closing in favor of PR 1387

2024-02-20 15:24 UTC, closed without merging